SELECT oha.order_number,
ep.attribute9,es.pickup_date,es.status,es.last_update_date,es.*
FROM APPS.WWT_LOOKUPS_ACTIVE_V      WL
,APPS.WWT_LOOKUPS_ACTIVE_V      WL_SETUP
,APPS.JTF_RS_SALESREPS          JRS
,APPS.PO_HEADERS_ALL            PHA
,APPS.PO_LINES_ALL              PLA
,APPS.PO_LINE_LOCATIONS_ALL     PLLA
,APPS.PO_REQUISITION_LINES_ALL  PRLA
,APPS.OE_ORDER_LINES_ALL        OLA
,APPS.WWT_OE_ORDER_HEADERS_ALL_V      OHA
,APPS.END_SHIPMENTS             ES
,APPS.END_PACKAGES              EP
,APPS.END_PACKAGES_GROUP        EPG
,APPS.HZ_CUST_SITE_USES_ALL     SUA
,APPS.HZ_CUST_ACCT_SITES_ALL    CAS
,APPS.HZ_PARTY_SITES            HPS
,APPS.HZ_LOCATIONS              HL
,APPS.HZ_PARTIES                HP
,APPS.WWT_SO_HEADERS_DFF        SHD
WHERE 1 = 1
AND OHA.order_number IN (6207012)
AND TO_NUMBER(WL_SETUP.ATTRIBUTE2) > 0
AND JRS.SALESREP_ID                = TO_NUMBER(WL_SETUP.ATTRIBUTE2)
AND OHA.SALESREP_ID                = JRS.SALESREP_ID
AND WL.LOOKUP_TYPE                 = 'WWT_OM_LINE_FLOW_CONTROLS'
AND WL.ATTRIBUTE2                  = 'DROP_SHIP'
AND OHA.SOLD_TO_ORG_ID             = NVL(WL_SETUP.ATTRIBUTE1, OHA.SOLD_TO_ORG_ID)
AND WL_SETUP.LOOKUP_TYPE                = 'WWT_ASN_OUTBOUND_EXTRACT'
AND WL_SETUP.ATTRIBUTE11                = 'Y'
--AND (WL_SETUP.ATTRIBUTE22 IS NULL OR (WL_SETUP.ATTRIBUTE22 IS NOT NULL AND OLA.SUBINVENTORY  IN  (SELECT /*+ CARDINALITY (ct 3) */ COLUMN_VALUE
--FROM TABLE (SELECT CAST (apps.wwt_utilities.wwt_string_to_table_fun
--(WL.ATTRIBUTE22, ',')
--AS wwt_string_to_table_type)
--FROM DUAL) ct)))
AND OLA.SHIP_FROM_ORG_ID = NVL(WL_SETUP.ATTRIBUTE23,OLA.SHIP_FROM_ORG_ID)
AND OHA.HEADER_ID                  = SHD.HEADER_ID (+)
AND NVL(SHD.ATTRIBUTE61, 'N/A')    = NVL(WL_SETUP.ATTRIBUTE19, NVL(SHD.ATTRIBUTE61, 'N/A'))
AND TO_CHAR( OLA.LINE_TYPE_ID )    = WL.ATTRIBUTE1
AND OLA.ORDERED_QUANTITY > 0
AND OLA.SPLIT_FROM_LINE_ID IS NULL
AND OLA.ATTRIBUTE20                = TO_CHAR(PRLA.REQUISITION_LINE_ID)
AND PLLA.LINE_LOCATION_ID          = PRLA.LINE_LOCATION_ID
AND PLLA.PO_LINE_ID                = PLA.PO_LINE_ID
AND PHA.ATTRIBUTE9                 = TO_CHAR( JRS.SALESREP_ID )
AND OHA.SHIP_TO_ORG_ID             = SUA.SITE_USE_ID (+)
AND SUA.CUST_ACCT_SITE_ID          = CAS.CUST_ACCT_SITE_ID (+)
AND CAS.PARTY_SITE_ID              = HPS.PARTY_SITE_ID (+)
AND HPS.LOCATION_ID                = HL.LOCATION_ID (+)
AND HP.PARTY_ID                    = HPS.PARTY_ID
AND OLA.HEADER_ID                  = OHA.HEADER_ID
AND PHA.PO_HEADER_ID               = PLA.PO_HEADER_ID
AND EP.ERP_LINE_NUMBER             = PLA.LINE_NUM
AND EP.ERP_PO_NUMBER               = PHA.SEGMENT1
AND ES.PICKUP_DATE IS NOT NULL
AND (ES.STATUS                      NOT IN ('Cancelled', 'Closed', 'Open')
OR (ES.STATUS = 'Closed' AND ES.LAST_UPDATE_DATE >= TRUNC(SYSDATE) - 1)
)
AND ES.SHIPMENT_ID                 = EP.SHIPMENT_ID
--AND EP.ATTRIBUTE9                  IS NULL
AND EP.PACKAGE_GROUP_ID            = EPG.PACKAGE_GROUP_ID (+)
;
WWT_ASN_OUTBOUND_EXTRACT
;