SELECT PG.NAME, OH.HEADER_ID, OH.ORIG_HEADER_ID,OH.CUSTOMER_PO_NUMBER, OH.PROCESS_GROUP_ID,OH.SOURCE, OH.CUSTOMER_PO_NUMBER, OH.WWT_ATTRIBUTE50, OH.LAST_UPDATE_DATE, OH.LAST_UPDATED_BY, OH.STATUS, OH.STATUS_MESSAGE, OH.BATCH_ID, OH.CREATED_BY,OH.CREATION_DATE, COUNT(OL.LINE_ID) LINE_COUNT, OH.ORG_ID
FROM APPS.WWT_STG_ORDER_HEADERS_V OH,
APPS.WWT_STG_ORDER_LINES OL,
APPS.WWT_OM_PROCESS_GROUPS PG
WHERE 1=1
--AND OH.STATUS in ('IN PROCESS', 'UNPROCESSED', 'IN QUEUE', 'PENDING REPROCESS', 'IN REPROCESS QUEUE','ITEM_PENDING') --,'ERROR')
AND OH.CREATION_DATE > SYSDATE - 120
--and oh.creation_date >= to_date('16-APR-2012 22:00:00','DD-MON-YYYY HH24:MI:SS') 
--and PG.NAME = 'Alcatel-Lucent'
--and PG.NAME like '%Callout-Generic'
--and OH.CUSTOMER_PO_NUMBER in ('15CN011190','JM800910280A1')
AND OH.HEADER_ID = OL.HEADER_ID
AND OH.HEADER_ID in (21505293)
AND OH.PROCESS_GROUP_ID = PG.PROCESS_GROUP_ID
GROUP BY PG.NAME, OH.HEADER_ID, OH.ORIG_HEADER_ID, OH.PROCESS_GROUP_ID, OH.SOURCE,OH.CUSTOMER_PO_NUMBER, OH.WWT_ATTRIBUTE50, OH.LAST_UPDATE_DATE, OH.STATUS, OH.STATUS_MESSAGE, OH.BATCH_ID, OH.CREATION_DATE, OH.LAST_UPDATED_BY, OH.CREATED_BY,OH.ORG_ID
--ORDER BY HEADER_ID DESC
--ORDER BY OH.CREATION_DATE DESC 
ORDER BY OH.LAST_UPDATE_DATE DESC
;   
select header_id,status,status_message from APPS.WWT_STG_ORDER_HEADERS_V
where 1=1
and status = 'IN PROCESS'
;