SELECT
PH.CREATION_DATE PO_CREATION_DATE
FROM
APPS.PO_HEADERS_ALL PH,
/*APPS.PO_VENDORS PV,*/
/*Commented by DTT R12 Upgrade Team on <<2015-02-05>> by << Vineesha Mekala >>*/
APPS.AP_SUPPLIERS PV,
/*Added by DTT R12 Upgrade Team on <<2015-02-05>> by << Vineesha Mekala >>*/
/*APPS.PO_VENDOR_SITES_ALL PVS,*/
/*Commented by DTT R12 Upgrade Team on <<2015-02-05>> by << Vineesha Mekala >>*/
APPS.AP_SUPPLIER_SITES_ALL PVS,
/*Added by DTT R12 Upgrade Team on <<2015-02-05>> by << Vineesha Mekala >>*/
APPS.PO_VENDOR_CONTACTS PVC,
APPS.AP_TERMS_TL ATT,
APPS.FND_CURRENCIES_VL FCC,
APPS.PER_ADDRESSES PA,            -- Buyer Information
APPS.PER_PEOPLE_F PPF,            -- Buyer Information
APPS.WSH_LOCATIONS WSH,          -- Bill to Information
APPS.HR_LOCATIONS HR,            -- Bill To Information
APPS.WSH_LOCATIONS WSH2,            -- Ship To Information
APPS.FINANCIALS_SYSTEM_PARAMS_ALL FSP,
APPS.WWT_METRIC_PROGRAMS MP,
APPS.JTF_RS_SALESREPS SR
WHERE
PH.VENDOR_SITE_ID = P_VENDOR_SITE_ID   -- Input Parameters (P_VENDOR_SITE_ID)
AND PH.VENDOR_ID = P_VENDOR_ID           -- Input Parameters (VENDOR_ID)
AND PH.TYPE_LOOKUP_CODE = 'STANDARD'
AND PH.XML_SEND_DATE IS NULL     -- PO has not been sent
AND NVL(PH.APPROVED_FLAG,'N') = 'Y'
AND NVL(PH.CANCEL_FLAG,'N') = 'N'
AND NVL(PH.USER_HOLD_FLAG,'N') = 'N'
AND PV.VENDOR_ID = PH.VENDOR_ID
AND PVS.VENDOR_SITE_ID = PH.VENDOR_SITE_ID
AND PVS.ORG_ID = PH.ORG_ID
AND PH.VENDOR_CONTACT_ID = PVC.VENDOR_CONTACT_ID (+)
AND PH.TERMS_ID = ATT.TERM_ID (+)
AND ATT.language(+) = SYS_CONTEXT('USERENV', 'LANG')  -- CHG21527 MLS Development Changes
AND FCC.CURRENCY_CODE = PH.CURRENCY_CODE
AND PPF.PERSON_ID = PH.AGENT_ID
AND PPF.EMPLOYEE_NUMBER IS NOT NULL
AND TRUNC(SYSDATE) BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
AND PA.PERSON_ID (+) = PPF.PERSON_ID
AND PA.PRIMARY_FLAG (+) = 'Y'
AND PA.DATE_FROM (+) <= TRUNC(SYSDATE)
AND NVL(PA.DATE_TO (+),TRUNC(SYSDATE)) >= TRUNC(SYSDATE)
AND PH.BILL_TO_LOCATION_ID = WSH.WSH_LOCATION_ID (+)
AND WSH.WSH_LOCATION_ID = HR.LOCATION_ID (+)
AND PH.SHIP_TO_LOCATION_ID (+)= WSH2.WSH_LOCATION_ID
AND FSP.ORG_ID = PH.ORG_ID
AND PH.ORG_ID = SR.ORG_ID (+)
AND TO_NUMBER(PH.ATTRIBUTE9) = SR.SALESREP_ID (+)
AND TO_NUMBER(SR.ATTRIBUTE2) = MP.PROGRAM_ID (+)
AND (PH.CREATION_DATE >= P_START_DATE OR P_START_DATE IS NULL) -- Input Parameters (P_START_DATE)
AND (PH.CREATION_DATE <= P_END_DATE OR P_END_DATE IS NULL)