SELECT *
FROM APPS.WWT_LOOKUPS_ACTIVE_V
WHERE LOOKUP_TYPE = 'WWT_WM_RECEIVE_EMAIL'
--AND (UPPER(?) LIKE UPPER(ATTRIBUTE1) OR ATTRIBUTE1 IS NULL)
AND (UPPER('96500.0000060122,KAISER FOUNDATION HOSPITALS,AN-ORD-EID:prod:bb3qbyy4d6go6x2hg:297:') LIKE UPPER(ATTRIBUTE2) OR ATTRIBUTE2 IS NULL)
--AND (UPPER(?) LIKE UPPER(ATTRIBUTE3) OR ATTRIBUTE3 IS NULL)
AND (UPPER('.xml') LIKE UPPER(ATTRIBUTE4) OR ATTRIBUTE4 IS NULL)
;
select *
from APPS.WWT_WM_EMAIL_HEADERS
where 1=1
and header_id = 104159
;
WWT_WM_EMAILS
;
select * from apps.WWT_WM_EMAIL_ATTACHMENTS
;